---
slug: examples
title: "Examples for your R package in manual pages"
authors:
  - Maëlle Salmon
date: "2020-01-15"
tags:
- package development
output: 
  html_document:
    keep_md: true
---

After posts exploring [READMEs](/2019/12/03/readmes/), [URLs in DESCRIPTION](/2019/12/10/urls/), today we shall look at another important aspect of documentation: examples in the manual pages of your functions! Why write them, how to write them, and how to control their execution in different contexts (CRAN or not :wink:).

## Why to write examples in manual pages?

We've made the point for users discovering packages through READMEs. Now, for functions, they might type `?foo` or open a `pkgdown` reference page and go straight to the example parts rather than read the previous sections (about parameters, details, etc). 

Users might do that either to get a quick feel for how the functions work, or refresh their memories of it. Say you discovered the [great `pkgsearch` package](/2019/11/26/pkgsearch/) and decided to try it out. You might look at the local [or online](https://r-hub.github.io/pkgsearch/reference/index.html) reference index and then nagivate to [the help for `package_search()`](https://r-hub.github.io/pkgsearch/reference/pkg_search.html) to [read examples](https://r-hub.github.io/pkgsearch/reference/pkg_search.html#examples).

Therefore, ideally your package should have examples for every function. The long-form docs (README, vignette) can still show functions working together and give a bigger picture, but adding executable code to your manual pages is crucial.

## How to run examples

As the user of an R package, how can you run examples you see in a package doc? (This is useful to know as a developer too!)

### How to run all examples from a man page

Locally, you could run

```r
example("pkg_search", package = "pkgsearch")
```

or 

```r
library("pkgsearch)
example("pkg_search")
```

As a side-effect, this makes all objects created in the example(s) available in your workspace.

### How to run specific examples from a man page

If you want to run only one of the examples you're reading

* You can select the lines and then run Command+Enter (Ctrl+Enter on Linux), be it in the R GUI or in RStudio. Below is a screenshot created by [Mine Çetinkaya-Rundel](https://twitter.com/minebocek) when she curated the [We are R-Ladies Twitter account](https://twitter.com/WeAreRLadies).

```{r echo=FALSE}

blogdown::shortcode("tweet", "1064734591641104384")
```

* From an online `pkgdown` website, you'd use the copy button and then paste the result in your R console.

## How to write examples?

In an Rd file, examples are inside `\examples{}` e.g.

```r
\examples{
  # basic usage of foo
  foo(basic = TRUE)
  # elaborate usage of foo
  foo(basic = FALSE)
}
```

But usually nowadays docs are generated by `roxygen2` so your examples can either

* exist after the `@examples` tag

```r
#' @examples
#' # basic usage of foo
#' foo(basic = TRUE)
#' # elaborate usage of foo
#' foo(basic = FALSE)
```

* exist in an R script that you'd source from the docs i.e.

```r
#' @example man/examples/foo.R
```

and in `man/examples/foo.R`

```r
# basic usage of foo
foo(basic = TRUE)
# elaborate usage of foo
foo(basic = FALSE)
``` 

The former solution (`@examples` tag: examples with other docs for the function) means you can work on the function code and examples at the same time more smoothly but all your lines start with `#'`; the latter solution (`@example` tag without an s: examples in dedicated files) means you can write examples as usual R code without `#'`. 

## How to know there are enough examples?

You could judge whether the man page of each function shows the most important behaviours by reading said man pages. You could also use the output of [`covr::package_coverage(<path-to-your-package>, type = "examples")`](https://covr.r-lib.org/reference/package_coverage.html) to reveal major gaps!

## How to safeguard examples?

Examples are supposed to be _executable_ i.e. to run without error. As writing in ["Writing R Extensions"](https://cran.r-project.org/doc/manuals/R-exts.html#index-_005cdontrun), _"By default, text inside `\examples{}` will be displayed in the output of the help page and run by `example()` and by `R CMD check`."_.

Now comes one of the trickiest aspects of creating examples for the manual pages: how to execute them only they work? We're not encouraging cheating but

* Examples can show an error, to exemplify the behaviour of the function in such cases.
* Examples can need user setup such as storing an API key in `.Renviron`.
* Examples can be too long for `R CMD check`.

Thankfully there are few toggles that you can use for your examples. From "Writing R extensions", _"You can use `\dontrun{}` for text that should only be shown, but not run, and `\dontshow{}` for extra commands for testing that should not be shown to users"_ and _"Finally, there is `\donttest`, used (at the beginning of a separate line) to mark code that should be run by example() but not by R CMD check (by default: the option `--run-donttest` can be used)."_. That's a lot of information to process, but `roxygen2` docs feature [a handy reference table](https://roxygen2.r-lib.org/articles/rd.html#functions).

To complicate things a bit more, `example()` and `R CMD check` have toggles too! You could run `example(<topic>, run.dontrun = TRUE)` and `R CMD check` with the `--run-donttest` options. :dizzy_face:

Here's a summary

* Example that works out of the box but long or interactive :arrow_right: donttest (used [19,065 times in CRAN packages at the time of writing](https://github.com/search?utf8=%E2%9C%93&q=%22%5Cdontrun%7B%22+user%3Acran+extension%3ARd&type=Code&ref=advsearch&l=&l=))

* Example that doesn't work out of the box or doesn't work at all :arrow_right: dontrun (used [2,019 times in CRAN packages at the time of writing](https://github.com/search?utf8=%E2%9C%93&q=%22%5Cdontrun%7B%22+user%3Acran+extension%3ARd&type=Code&ref=advsearch&l=&l=))

> For a CRAN submission you might be told to use `donttest` for examples using a token.

* Example where you want to [sneakily a subset of the example data](https://kbroman.org/pkg_primer/pages/cran.html) (to make it run faster) :arrow_right: dontshow (used [1,209 times in CRAN packages at the time of writing](https://github.com/search?q=%22%5Cdontshow%7B%22+user%3Acran+extension%3ARd&type=Code))

Depending on why you choose to pack some examples in `\dontrun`, you might enjoy the [`run_dont_run` option of `pkgdown::build_site()`](https://pkgdown.r-lib.org/reference/build_site.html#arguments), e.g. if your examples depend on having authentication tokens that _are_ present when building the pkgdown website.

## How to check your examples?

You could run `R CMD check` with the options you want. Or you could use 

* [`devtools::run_examples()`](https://devtools.r-lib.org/reference/run_examples.html) that has `run` and `test` toggles.

* [`testthat::test_examples()`](https://testthat.r-lib.org/reference/test_examples.html). This function doesn't pass any argument to `tools::Rd2ex()` that it uses to extract the examples from the docs, so it will test `donttest` examples but not test `dontrun` examples (`commentDontrun = TRUE, commentDonttest = FALSE`). You can use `test_examples()` in a testthat test file to have examples run by `devtools::test()`.

## What can't code in examples do?

Two items from the [CRAN policies](https://cran.r-project.org/web/packages/policies.html) should be borne in mind when creating examples (and when choosing dontrun/donttest/dontshow toggles :wink:).

* _"Examples should run for no more than a few seconds each: they are intended to exemplify to the would-be user how to use the functions in the package."_ :hourglass:

* _"The code and examples provided in a package should never do anything which might be regarded as malicious or anti-social."_  :smiling_imp: The policies give examples of such behaviour such as _"Packages should not write in the user’s home filespace (including clipboards), nor anywhere else on the file system apart from the R session’s temporary directory"_. So make good use of `tempdir()`!

## Conclusion

In this post we answered questions around the preparation of examples for manual pages of R packages. If you wish there were even more flexibility, be on the lookout for future developments for examples written with `roxygen2`, [for instance check out the WIP `roxygen2labs` package](https://github.com/gaborcsardi/roxygenlabs#conditional-examples).
