---
slug: distribute-data
title: "How to distribute data with your R packages"
authors:
  - Maëlle Salmon
date: "2020-05-29"
tags:
- package development
- standards
- data
output: hugodown::hugo_document
---

```{r setup, include=FALSE}
# Options to have images saved in the post folder
# And to disable symbols before output
knitr::opts_chunk$set(fig.path = "", comment = "")

# knitr hook to make images output use Hugo options
knitr::knit_hooks$set(
  plot = function(x, options) {
    hugoopts <- options$hugoopts
    paste0(
      "{{<figure src=",
      '"', x, '" ',
      if (!is.null(hugoopts)) {
        glue::glue_collapse(
          glue::glue('{names(hugoopts)}="{hugoopts}"'),
          sep = " "
        )
      },
      ">}}\n"
    )
  }
)

# knitr hook to use Hugo highlighting options
knitr::knit_hooks$set(
  source = function(x, options) {
  hlopts <- options$hlopts
    paste0(
      "```r ",
      if (!is.null(hlopts)) {
      paste0("{",
        glue::glue_collapse(
          glue::glue('{names(hlopts)}={hlopts}'),
          sep = ","
        ), "}"
        )
      },
      "\n", glue::glue_collapse(x, sep = "\n"), "\n```\n"
    )
  }
)
```

Sometimes you'll want a package of yours to have readily access to some data: to show what a function of yours can accomplish with a dataset, to show how your package can help tidy a messy data format, to test the package, or even to just distribute the data for teaching purposes.
Now, _how_ to provide data with/for your package is a recurring theme in [R package development channels](/2019/04/11/r-package-devel/).
In this post, we shall present various ways to distribute data with/for an R package, depending on the data use case and on its size.

_Thanks to the R connoisseurs [Thomas Vroylandt](https://tvroylandt.netlify.app/), [Sébastien Rochette](https://statnmap.com/) and [Hugo Gruson](https://www.normalesup.org/~hgruson/) for providing some inspiration and resources for this post! :pray: [^grrr]_

## Data in your package

Sometimes the data can be _vendored_[^vendor] i.e. live in your package source, and even in your package built and installed versions.
An excellent overview of the different cases is provided in the [R packages book by Hadley Wickham and Jenny Bryan](https://r-pkgs.org/data.html); without forgetting the reference "Writing R Extensions" especially useful in cases such as [_"where a dataset or one of its components is of an S4 class"_](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Data-in-packages).

### Data just

### Data as small as possible

As "Writing R Extensions" underlines, for data under `data/` and, _"If your package is to be distributed, do consider the resource implications of large datasets for your users: they can make packages very slow to download and use up unwelcome amounts of storage space, as well as taking many seconds to load."_.
So what do you do?

* You can _compress_ the data, internal or external.

* You can refer the next section of this post and have data live outside of your package!

## Data outside of your package

Now, sometimes the data is too big to be in your package, or follows a different development cycle i.e. is updated more or less often.
What can you do about that?
Well, have data live somewhere else and download it as needed, potentially saving it locally (which still uses potentially "unwelcome amounts of storage space", so warn the user)


## Conclusion

In this post we went over different setups allowing you to distribute data with or for your R package: some standard locations in your package source (`inst/extdata/`, `data/`, `R/sysdata.rda`); locations outside of your package (using `drat`, `git-LFS`, GitHub releases via `piggyback`, a web API you'd build yourself), that your package would know how to access, and potentially save locally (in an app dir, or using a tool like `bowerbird`).
Do _you_ have a "data and R package" setup you'd like to share?
Please comment below!

[^grrr]: In a conversation in the friendly French-speaking R Slack workspace -- where we'd write _connaisseurs_, not _connoisseurs_. If you want to join us, follow [the invitation link](https://github.com/frrrenchies/frrrenchies#cat-chat-et-discussions-instantan%C3%A9es-cat). _À bientôt !_
[^vendor]: Now that you know the word _vendor_, [_" to bundle one's own, possibly modified version of dependencies with a standard program."_](https://www.wordhippo.com/what-is/the-verb-for/vendor.html), you can use your search engine to find and enjoy debates around vendoring or not. You're welcome.