--- 
slug: oauth-2.0
title: "How to deal with OAuth2.0 in R packages?" 
authors: 
- Maëlle Salmon 
date: "2021-01-05" 
tags: 
- package development 
- security
output: hugodown::hugo_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(fig.path = "", comment = "")
# knitr hook to make images output use Hugo options
knitr::knit_hooks$set(
  plot = function(x, options) {
    hugoopts <- options$hugoopts
    paste0(
      "{{<figure src=",
      '"', x, '" ',
      if (!is.null(hugoopts)) {
        glue::glue_collapse(
          glue::glue('{names(hugoopts)}="{hugoopts}"'),
          sep = " "
        )
      },
      ">}}\n"
    )
  }
)

```

If you see the web API you want to wrap uses OAuth2.0 rather than a simple API key for authentication, are you happy or do you get nervous?
If you get nervous, this post is for you!
We shall demistify OAuth2.0 a bit, and provide links to useful resources.

## What is OAuth 2.0?

OAuth 2.0 is the most recent standard of OAuth, coming after OAuth 1.0.
But you were probably not looking for this kind of answer. :smile_cat:

OAuth 2.0 is a way for a resource server (say, Twitter API) to grant access to (part of) your account to an app (say, a Twitter alternative app, or rtweet) on your behalf.
It is safer than previous industry standards, see the video below.

```{=html}
{{< youtube KT8ybowdyr0 >}}
```

In practice, with OAuth 2.0 there is a _dance_ i.e. a series of requests and redirects between the server and the third-party app, launched by you when starting to install an app, and validating by you as one of the step is your clicking something like "Yes, I grant access to this and that right on my Twitter account, to the app Twitter Lite".
Aaron Parecki (featured in the video above) has a great write-up on ][simplified OAuth 2.0](https://aaronparecki.com/oauth-2-simplified/).

To use things on the server one needs an access token. The whole point of the OAuth 2.0 dance is to get an access token. Often you will also get a refresh token. The refresh token allows to get issued a new access token _without any interactivity i.e. no need for the user to click_. A common validity period for an access token would be 24 hours, for a refresh token one year, and often the refresh token is re-usable.

Now while this all makes perfect sense when you are developing an actual third-party app, for interactive usage... when all you want is an R package that can be used in scripts running on a server, it's much less clear.

## How do you use OAuth 2.0?

When writing an R package wrapping an API using OAuth 2.0 you'll need the user to grant access to an "app", which will allow to create

## What are your OAuth 2.0 secret credentials?

## How to you test OAuth 2.0?

## Conclusion

In this post we offered a round-up around OAuth 2.0.
We hope it helped clarify this tool that's not very natural for R developers.
Please share any further tip below!
